package com.hereliesaz.halfhashedkitty.ui.tabs

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import com.hereliesaz.halfhashedkitty.PiControlViewModel
import com.hereliesaz.halfhashedkitty.ui.screens.ScannerScreen

@Composable
fun PiControlTab(piControlViewModel: PiControlViewModel, onShowInstructions: () -> Unit) {
    Column(
        modifier = Modifier
            .fillMaxSize()
    ) {
        ScreenTitle("Pi Control", onShowInstructions)
        ScannerScreen(
            instructionText = "To connect to a Raspberry Pi running the necessary tools, please scan the QR code generated by the Pi.",
            onQrCodeScanned = { qrCodeValue ->
                piControlViewModel.onQrCodeScanned(qrCodeValue)
            }
        )
    }
}