package com.hereliesaz.halfhashedkitty.ui.tabs

import androidx.compose.runtime.Composable
import com.hereliesaz.halfhashedkitty.PiControlViewModel
import com.hereliesaz.halfhashedkitty.ui.screens.ScannerScreen

@Composable
fun PiControlTab(piControlViewModel: PiControlViewModel) {
    ScannerScreen(
        instructionText = "To connect to a Raspberry Pi running the necessary tools, please scan the QR code generated by the Pi.",
        onQrCodeScanned = { qrCodeValue ->
            piControlViewModel.onQrCodeScanned(qrCodeValue)
        }
    )
}
